name: CI
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Debug once; remove after CI is green
      - name: Debug workspace
        run: |
          pwd
          ls -la
          echo "----- head pyproject.toml -----"
          head -n 20 pyproject.toml || true

      # Validate pyproject.toml (catch BOM/format issues)
      - name: Validate pyproject.toml with tomllib
        run: |
          python - <<'PY'
          import pathlib, tomllib
          p = pathlib.Path('pyproject.toml')
          b = p.read_bytes()
          print("First bytes:", b[:4])  # must NOT be b'\xef\xbb\xbf'
          with open('pyproject.toml', 'rb') as f:
            tomllib.load(f)             # correct: parse from binary file
          print("pyproject.toml OK")
          PY

      - run: python -m pip install --upgrade pip

      # Try editable install; if it fails, run tests from source
      - name: Install and run tests (with fallback)
        shell: bash
        run: |
          set -euxo pipefail
          if pip install -e .[dev]; then
            pytest -q
          else
            echo "Editable install failed; running tests from source."
            pip install pytest pyyaml ruff
            PYTHONPATH=. pytest -q
          fi
