name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: python -m pip install --upgrade pip
      - run: pip install pytest pyyaml
      - name: Debug workspace (once)
        run: |
          pwd
          ls -la
          head -n 20 pyproject.toml || true
      - run: PYTHONPATH=. pytest -q
